name: DocumentationDev

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and publish documentation during development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get install -y doxygen
          python3 -m pip install jinja2 Pygments
          
      - name: Build
        run: |
          cmake -Hdocumentation -Bbuild
          cmake --build build --target GenerateDocs
          
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doxygen/html
